---
spring:
  jpa:
    open-in-view: false
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;
    username: test
    password: test
    hikari:
      maximum-pool-size: 2
  output:
    ansi:
      enabled: always
